"""Language statistics for the README badges.

Counts the non-blank lines of each language in the repository, so the percentages
describe what a reader actually finds in the tree.

Three kinds of file are deliberately kept OUT of the code mix, and reported in
their own section instead, because counting them makes the percentages lie:

  * generated files -- ``src/dxcc_tables.py`` is built from the ARRL list, and
    ``web/browser.html`` is generated from ``web/index.html`` with
    ``docs/web.html`` as a byte-identical copy for GitHub Pages.  Counting the
    browser page twice overstated HTML by 1,798 lines before this was fixed;
  * dev-only probe scripts under ``tests/adversarial/`` -- one-off diagnostics
    for bugs already fixed, not part of the product nor of the suite CI runs;
  * prose and configuration (Markdown, TOML, plain text).

Run it and copy the three percentages into the badges and the language section of
both READMEs.
"""

import io
import os
import sys
from collections import Counter

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8",
                              errors="replace")

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

#: extension -> language
LANGUAGES = {
    ".py": "Python",
    ".html": "HTML",
    ".bat": "Batchfile",
    ".md": "Markdown",
    ".toml": "TOML",
    ".yml": "YAML",
    ".yaml": "YAML",
    ".css": "CSS",
    ".js": "JavaScript",
    ".txt": "Text",
    ".go": "Go",
    ".json": "JSON",
    ".spec": "Python",
}
#: Directories that are not part of the readable source.  release/ holds the
#: release ZIPs: hundreds of megabytes, and nothing in them is source.
SKIP_DIRS = {".git", "dist", "build", "__pycache__", ".ruff_cache",
             "node_modules", ".github", "release"}
#: Generated or derived files, listed explicitly with the reason.  Counting
#: these double-counts a source that is already in the tree.
GENERATED = {
    "src/dxcc_tables.py":
        "generated by tools/build_dxcc.py from tools/data/arrl_dxcc_2026.txt",
    "web/browser.html":
        "generated by tools/build_browser_page.py from web/index.html",
    "docs/web.html":
        "byte-identical copy of web/browser.html, published by GitHub Pages",
    "tools/data/arrl_dxcc_2018.txt": "parsed ARRL data",
    "tools/data/arrl_dxcc_2026.txt": "parsed ARRL data",
    "docs/index.html":
        "the GitHub Pages landing page: documentation, not the application",
}
#: One-off diagnostic scripts, not part of the product or of the CI suite.
SKIP_DIRS_EXTRA = {os.path.join("tests", "adversarial")}
SKIP_FILES = set(GENERATED)


def main():
    counts = Counter()
    files = Counter()
    for base, dirs, names in os.walk(ROOT):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for name in names:
            path = os.path.join(base, name)
            rel = os.path.relpath(path, ROOT).replace("\\", "/")
            ext = os.path.splitext(name)[1].lower()
            language = LANGUAGES.get(ext)
            if not language:
                continue
            try:
                text = open(path, encoding="utf-8", errors="replace").read()
            except OSError:
                continue
            lines = sum(1 for line in text.splitlines() if line.strip())
            if not lines:
                continue
            if rel in SKIP_FILES:
                # Generated, dev-only or documentation: reported separately so it
                # neither disappears nor inflates the code mix.
                counts[f"~{rel}"] += lines
                files[f"~{rel}"] += 1
                continue
            if any(rel.startswith(extra.replace(os.sep, "/") + "/")
                   for extra in SKIP_DIRS_EXTRA):
                counts["~tests/adversarial"] += lines
                files["~tests/adversarial"] += 1
                continue
            if language in ("Markdown", "Text", "JSON", "YAML", "TOML"):
                # Prose and config are reported but kept out of the code mix.
                counts[f"_{language}"] += lines
                files[f"_{language}"] += 1
                continue
            counts[language] += lines
            files[language] += 1

    prose = {k[1:]: v for k, v in counts.items() if k.startswith("_")}
    excluded = {k[1:]: v for k, v in counts.items() if k.startswith("~")}
    code = {k: v for k, v in counts.items()
            if not k.startswith(("_", "~"))}
    total = sum(code.values())

    print("=== code languages (share of code lines) ===")
    for language, lines in sorted(code.items(), key=lambda kv: -kv[1]):
        pct = 100.0 * lines / total if total else 0
        print(f"  {language:14} {lines:7} lines  {pct:5.1f}%  "
              f"({files[language]} files)")
    print(f"  {'TOTAL':14} {total:7} lines")

    print()
    print()
    print("=== excluded from the code mix ===")
    for label, lines in sorted(excluded.items(), key=lambda kv: -kv[1]):
        reason = GENERATED.get(label, "")
        if label == "tests/adversarial":
            reason = "one-off diagnostics, not part of the product"
        print(f"  {label:28} {lines:7} lines  ({files['~' + label]} files)")
        if reason:
            print(f"      {reason}")

    print()
    print("=== prose and configuration (not part of the code mix) ===")
    for language, lines in sorted(prose.items(), key=lambda kv: -kv[1]):
        print(f"  {language:14} {lines:7} lines  ({files['_' + language]} files)")

    print()
    print("=== shields.io badge values ===")
    for language, lines in sorted(code.items(), key=lambda kv: -kv[1]):
        pct = 100.0 * lines / total if total else 0
        print(f"  {language} {pct:.1f}%")

    return code, total


if __name__ == "__main__":
    main()
